title = "styleguide"
base_url = "https://styleguide.fermyon.app"
about = "Fermyon's Brand Guide & Design Styleguide"

[extra]
copyright = "Ronan Flynn-Curran"
github = "https://github.com/fermyon/styleguide"